# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `schematist` gem.
# Please instead update this file by running `bin/tapioca gem schematist`.


module Schematist; end
Schematist::ANNOTATIONS = T.let(T.unsafe(nil), Hash)
Schematist::CORE_KEYWORDS = T.let(T.unsafe(nil), Hash)

module Schematist::DSL
  include ::Schematist::DSL::SchemaBuilders
  include ::Schematist::DSL::PrimitiveTypes
  include ::Schematist::DSL::ComplexTypes
  include ::Schematist::DSL::Conditionals
  include ::Schematist::DSL::Utilities
end

module Schematist::DSL::ComplexTypes
  def all_of(name = T.unsafe(nil), description: T.unsafe(nil), required: T.unsafe(nil), requires: T.unsafe(nil), **options, &block); end
  def any_of(name = T.unsafe(nil), description: T.unsafe(nil), required: T.unsafe(nil), requires: T.unsafe(nil), **options, &block); end
  def array(name = T.unsafe(nil), description: T.unsafe(nil), required: T.unsafe(nil), requires: T.unsafe(nil), **options, &block); end
  def none_of(name = T.unsafe(nil), description: T.unsafe(nil), required: T.unsafe(nil), requires: T.unsafe(nil), **options, &block); end
  def object(name = T.unsafe(nil), description: T.unsafe(nil), required: T.unsafe(nil), requires: T.unsafe(nil), **options, &block); end
  def one_of(name = T.unsafe(nil), description: T.unsafe(nil), required: T.unsafe(nil), requires: T.unsafe(nil), **options, &block); end
  def optional(name, description: T.unsafe(nil), &block); end
  def raw(name, schema = T.unsafe(nil), required: T.unsafe(nil), requires: T.unsafe(nil)); end
  def tuple(name = T.unsafe(nil), description: T.unsafe(nil), required: T.unsafe(nil), requires: T.unsafe(nil), **options, &block); end
end

class Schematist::DSL::ConditionalBuilder
  def initialize; end

  def empty?; end
  def method_missing(name, *, **, &); end
  def required_fields; end
  def requires(*fields); end
  def to_schema; end
  def validates(field, **options); end
  def validations_empty?; end

  private

  def additional_properties_set?; end
  def branch_properties; end
  def branch_required; end
  def required; end
  def respond_to_missing?(name, include_private = T.unsafe(nil)); end
  def validations; end
end

Schematist::DSL::ConditionalBuilder::VALIDATES_KEY_MAP = T.let(T.unsafe(nil), Hash)

class Schematist::DSL::ConditionalContext
  def initialize(then_builder, else_builder); end

  def method_missing(name, *, **, &); end
  def otherwise(&block); end

  private

  def respond_to_missing?(name, include_private = T.unsafe(nil)); end
end

module Schematist::DSL::Conditionals
  def conditions; end
  def dependencies; end
  def dependent(property, &block); end
  def given(condition = T.unsafe(nil), **properties, &block); end

  private

  def coerce_condition(value); end
  def merge_conditions(schema, schema_class); end
end

module Schematist::DSL::PrimitiveTypes
  def boolean(name = T.unsafe(nil), description: T.unsafe(nil), required: T.unsafe(nil), requires: T.unsafe(nil), **options, &block); end
  def integer(name = T.unsafe(nil), description: T.unsafe(nil), required: T.unsafe(nil), requires: T.unsafe(nil), **options, &block); end
  def null(name = T.unsafe(nil), description: T.unsafe(nil), required: T.unsafe(nil), requires: T.unsafe(nil), **options, &block); end
  def number(name = T.unsafe(nil), description: T.unsafe(nil), required: T.unsafe(nil), requires: T.unsafe(nil), **options, &block); end
  def string(name = T.unsafe(nil), description: T.unsafe(nil), required: T.unsafe(nil), requires: T.unsafe(nil), **options, &block); end
end

module Schematist::DSL::SchemaBuilders
  def all_of_schema(description: T.unsafe(nil), unevaluated_properties: T.unsafe(nil), unevaluated_items: T.unsafe(nil), **annotations, &block); end
  def any_of_schema(description: T.unsafe(nil), unevaluated_properties: T.unsafe(nil), unevaluated_items: T.unsafe(nil), **annotations, &block); end
  def array_schema(description: T.unsafe(nil), of: T.unsafe(nil), min_items: T.unsafe(nil), max_items: T.unsafe(nil), unique: T.unsafe(nil), unevaluated_items: T.unsafe(nil), **annotations, &block); end
  def boolean_schema(description: T.unsafe(nil), enum: T.unsafe(nil), const: T.unsafe(nil), **annotations, &block); end
  def integer_schema(description: T.unsafe(nil), minimum: T.unsafe(nil), maximum: T.unsafe(nil), greater_than: T.unsafe(nil), less_than: T.unsafe(nil), multiple_of: T.unsafe(nil), enum: T.unsafe(nil), const: T.unsafe(nil), format: T.unsafe(nil), **annotations, &block); end
  def none_of_schema(description: T.unsafe(nil), unevaluated_properties: T.unsafe(nil), unevaluated_items: T.unsafe(nil), **annotations, &block); end
  def null_schema(description: T.unsafe(nil), enum: T.unsafe(nil), **annotations, &block); end
  def number_schema(description: T.unsafe(nil), minimum: T.unsafe(nil), maximum: T.unsafe(nil), greater_than: T.unsafe(nil), less_than: T.unsafe(nil), multiple_of: T.unsafe(nil), enum: T.unsafe(nil), const: T.unsafe(nil), format: T.unsafe(nil), **annotations, &block); end
  def object_schema(description: T.unsafe(nil), of: T.unsafe(nil), reference: T.unsafe(nil), min_properties: T.unsafe(nil), max_properties: T.unsafe(nil), unevaluated_properties: T.unsafe(nil), **annotations, &block); end
  def one_of_schema(description: T.unsafe(nil), unevaluated_properties: T.unsafe(nil), unevaluated_items: T.unsafe(nil), **annotations, &block); end
  def string_schema(description: T.unsafe(nil), enum: T.unsafe(nil), const: T.unsafe(nil), min_length: T.unsafe(nil), max_length: T.unsafe(nil), pattern: T.unsafe(nil), format: T.unsafe(nil), content_encoding: T.unsafe(nil), content_media_type: T.unsafe(nil), **annotations, &block); end
  def tuple_schema(description: T.unsafe(nil), of: T.unsafe(nil), min_items: T.unsafe(nil), max_items: T.unsafe(nil), unevaluated_items: T.unsafe(nil), **annotations, &block); end

  private

  def annotate(schema, annotations, schema_block = T.unsafe(nil)); end
  def build_object_schema(description, &block); end
  def collect_schema_block(&block); end
  def collect_schemas_from_block(&); end
  def determine_array_items(of, schema_block = T.unsafe(nil)); end
  def determine_object_reference(of, description = T.unsafe(nil)); end
  def schema_class_to_inline_schema(schema_class_or_instance); end
end

class Schematist::DSL::SchemaBuilders::SchemaBlock < ::Struct
  def keywords; end
  def keywords=(_); end
  def schemas; end
  def schemas=(_); end

  class << self
    def [](*_arg0); end
    def inspect; end
    def keyword_init?; end
    def members; end
    def new(*_arg0); end
  end
end

module Schematist::DSL::Utilities
  def define(name, &); end
  def keys(&block); end
  def keys_matching(pattern, &block); end
  def object_keywords; end
  def reference(schema_name); end

  private

  def add_property(name, definition, required:, requires: T.unsafe(nil)); end
  def add_property_or_self(name, definition, required:, requires: T.unsafe(nil)); end
  def merge_schema_keywords(schema, schema_class); end
  def primitive_type?(type); end
  def schema_class?(type); end
  def schema_for(schema_class); end
end

class Schematist::Error < ::StandardError; end

module Schematist::Helpers
  def schema(name = T.unsafe(nil), description: T.unsafe(nil), &block); end
end

class Schematist::InvalidArrayTypeError < ::Schematist::Error; end
class Schematist::InvalidObjectTypeError < ::Schematist::Error; end
class Schematist::InvalidSchemaError < ::Schematist::Error; end

class Schematist::InvalidSchemaTypeError < ::Schematist::Error
  def initialize(type); end
end

module Schematist::JsonOutput
  def to_json(*_args); end
  def to_json_schema; end

  private

  def json_compatible(value); end
  def resolve_runtime_values(value); end
  def schema_body; end
end

Schematist::JsonOutput::DRAFT_2020_12 = T.let(T.unsafe(nil), String)
class Schematist::LimitExceededError < ::Schematist::Error; end
Schematist::PRIMITIVE_TYPES = T.let(T.unsafe(nil), Array)

class Schematist::Schema
  include ::Schematist::JsonOutput
  extend ::Schematist::DSL::SchemaBuilders
  extend ::Schematist::DSL::PrimitiveTypes
  extend ::Schematist::DSL::ComplexTypes
  extend ::Schematist::DSL::Conditionals
  extend ::Schematist::DSL::Utilities
  extend ::Schematist::DSL

  def initialize(name = T.unsafe(nil), description: T.unsafe(nil)); end

  def method_missing(method_name, *, **, &); end
  def valid?; end
  def validate!; end

  private

  def respond_to_missing?(method_name, include_private = T.unsafe(nil)); end

  class << self
    def additional_properties(value = T.unsafe(nil)); end
    def anchor(*args); end
    def annotations; end
    def comment(*args); end
    def core_keywords; end
    def create(&block); end
    def default(*args); end
    def definitions; end
    def deprecated(*args); end
    def description(*args); end
    def dynamic_anchor(*args); end
    def dynamic_ref(*args); end
    def examples(*args); end
    def id(*args); end
    def max_properties(value = T.unsafe(nil)); end
    def min_properties(value = T.unsafe(nil)); end
    def name(name = T.unsafe(nil)); end
    def properties; end
    def read_only(*args); end
    def required_properties; end
    def self_schema(definition = T.unsafe(nil)); end
    def title(*args); end
    def unevaluated_items(value = T.unsafe(nil)); end
    def unevaluated_properties(value = T.unsafe(nil)); end
    def valid?; end
    def validate!; end
    def vocabulary(*args); end
    def write_only(*args); end

    private

    def annotation(name, *args); end
    def core_keyword(name, *args); end
    def object_keyword(keyword, value); end
    def read_or_write(store, keyword, *args); end
  end
end

Schematist::VERSION = T.let(T.unsafe(nil), String)
class Schematist::ValidationError < ::Schematist::Error; end

class Schematist::Validator
  def initialize(schema_class); end

  def valid?; end
  def validate!; end

  private

  def extract_references(property); end
  def validate_circular_references!; end
  def visit(node, definitions, marks); end
end

Schematist::Validator::BLACK = T.let(T.unsafe(nil), Symbol)
Schematist::Validator::GRAY = T.let(T.unsafe(nil), Symbol)
Schematist::Validator::WHITE = T.let(T.unsafe(nil), Symbol)
