name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Linters
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Ruby
        uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          bundler-cache: true
      - name: Run type check
        run: bundle exec srb tc
      - name: Lint Ruby files
        run: bundle exec rubocop --fail-level error
      - name: Verify documentation
        run: bin/docs
      - name: Run tests
        run: bin/test
      - name: Verify gem RBIs are up-to-date
        run: bin/tapioca gem --verify
      - name: Verify duplicates in shims
        run: bin/tapioca check-shims
